"use client";
import { useState } from "react";
import { useDropzone } from "react-dropzone";
import { Upload, X } from "lucide-react";
import { createClient } from "@/supabase/client";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
const IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp"];
export function UploadPanel({ personId }: { personId: string }) { const [files, setFiles] = useState<File[]>([]); const [uploading, setUploading] = useState(false); const { getRootProps, getInputProps, isDragActive } = useDropzone({ onDrop: accepted => setFiles(current => [...current, ...accepted]), maxSize: 15 * 1024 * 1024, accept: { "image/*": [".jpg", ".jpeg", ".png", ".webp"], "application/pdf": [".pdf"], "application/zip": [".zip", ".rar"], "application/vnd.openxmlformats-officedocument.wordprocessingml.document": [".docx"], "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": [".xlsx"], "text/plain": [".txt"] } }); async function upload() { if (!files.length) return; setUploading(true); const supabase = createClient(); try { for (const file of files) { const image = IMAGE_TYPES.includes(file.type); const bucket = image ? "people-images" : "people-files"; const path = `${personId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "_")}`; const { error } = await supabase.storage.from(bucket).upload(path, file, { upsert: false }); if (error) throw error; const table = image ? "images" : "files"; const record = image ? { person_id: personId, path, alt: file.name } : { person_id: personId, path, name: file.name, mime_type: file.type, size: file.size }; const { error: dbError } = await supabase.from(table).insert(record); if (dbError) throw dbError; } setFiles([]); toast.success("Uploads concluídos"); } catch (error) { toast.error("Falha no upload", { description: error instanceof Error ? error.message : "Tente novamente" }); } finally { setUploading(false); } } return <section><h2 className="text-xl font-semibold">Adicionar arquivos</h2><div {...getRootProps()} className={`mt-4 cursor-pointer rounded-2xl border-2 border-dashed p-8 text-center transition ${isDragActive ? "border-primary bg-muted" : "border-border"}`}><input {...getInputProps()}/><Upload className="mx-auto mb-3"/><p className="font-medium">Arraste imagens e arquivos aqui</p><p className="mt-1 text-sm text-foreground/60">JPG, PNG, WEBP, PDF, ZIP, RAR, DOCX, XLSX e TXT — até 15 MB cada</p></div>{files.length > 0 && <div className="mt-4 space-y-2">{files.map((file, index) => <div className="flex items-center justify-between rounded-xl bg-muted p-3 text-sm" key={`${file.name}-${index}`}><span className="truncate">{file.name}</span><button aria-label={`Remover ${file.name}`} onClick={() => setFiles(current => current.filter((_, i) => i !== index))}><X size={18}/></button></div>)}<Button onClick={upload} disabled={uploading}>{uploading ? "Enviando..." : `Enviar ${files.length} arquivo(s)`}</Button></div>}</section> }
